### PR TITLE
Eauction

### PR DESCRIPTION
**Pull request by SlaOne**
changes for viewer and  some fixes

---

This change is [Reviewable](https://reviewable.io/reviews/openprocurement/robot_tests.broker.newtend/3)

### CODE REVIEW

**Comment by mykhaly** [comment]
Навіщо додавати в репозиторій стільки закоментованого коду?

---

Reviewed 2 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 18 unresolved discussions.

---

_[newtend.robot, line 141 at r1](https://reviewable.io:443/reviews/openprocurement/robot_tests.broker.newtend/3#-KReTw8p_P2y_VHOsjUv:-KReTw8p_P2y_VHOsjUw:by5ke24) ([raw file](https://github.com/openprocurement/robot_tests.broker.newtend/blob/417ade6cc393a2ba80ce935e31b464d9fb120acf/newtend.robot#L141)):_

> ``` RobotFramework
>   # Search in CAV didn't work for that time, when tests were written
>   # Sorry, for this!!
>   Click Element       xpath=//label[@for="66113000-5"]
> ```

Тут хардкод. @ykosaniak чому це потрапило в репозиторій?

---

_[newtend.robot, line 161 at r1](https://reviewable.io:443/reviews/openprocurement/robot_tests.broker.newtend/3#-KReUI3nlqQdS6x9dVOc:-KReUI3oVcNyaGn1eIn4:by5ke24) ([raw file](https://github.com/openprocurement/robot_tests.broker.newtend/blob/417ade6cc393a2ba80ce935e31b464d9fb120acf/newtend.robot#L161)):_

> ``` RobotFramework
>   Click Element                      xpath=//button[@class="btn btn-lg single-btn ng-binding"]  # ng-click="save()"
> 
>   ${delivery_end_date_formatted}      Get Substring      ${deliverydate_end_date}     0     10   # 2016-09-07
> ```

Тут хардкод. @ykosaniak чому це потрапило в репозиторій?

---

_[newtend.robot, line 267 at r1](https://reviewable.io:443/reviews/openprocurement/robot_tests.broker.newtend/3#-KReV3womE2R9sMeQi12:-KReV3womE2R9sMeQi13:b-fkyiua) ([raw file](https://github.com/openprocurement/robot_tests.broker.newtend/blob/417ade6cc393a2ba80ce935e31b464d9fb120acf/newtend.robot#L267)):_

> ``` RobotFramework
>   run keyword if  '${ARGUMENTS[0]}' == 'Newtend_Owner'   Click element   xpath=//span[@class="icon icon-newtend"]
>   log to console   ${ARGUMENTS[0]}
>   LOG TO CONSOLE   ${ARGUMENTS[1]}
> ```

Цього не має бути в репозиторії.

---

_[newtend.robot, line 314 at r1](https://reviewable.io:443/reviews/openprocurement/robot_tests.broker.newtend/3#-KReVIUr6Pfb74Gc0fqA:-KReVIUr6Pfb74Gc0fqB:b-fkyiua) ([raw file](https://github.com/openprocurement/robot_tests.broker.newtend/blob/417ade6cc393a2ba80ce935e31b464d9fb120acf/newtend.robot#L314)):_

> ``` RobotFramework
>   ${return_value}=   Отримати текст із поля і показати на сторінці   status
>   ${return_value}=   convert_nt_string_to_common_string   ${return_value}
>   log to console    ${return_value}
> ```

Цього не має бути в репозиторії.

---

_[newtend.robot, line 536 at r1](https://reviewable.io:443/reviews/openprocurement/robot_tests.broker.newtend/3#-KReVS7Y-uI93tDaLReH:-KReVS7Y-uI93tDaLReI:b-fkyiua) ([raw file](https://github.com/openprocurement/robot_tests.broker.newtend/blob/417ade6cc393a2ba80ce935e31b464d9fb120acf/newtend.robot#L536)):_

> ``` RobotFramework
>   Sleep  1
>   ${return_value}=   Get Text         xpath=//span[@class="answer-description ng-binding"]
>   log to console    ${return_value}
> ```

Цього не має бути в репозиторії.

---

_[newtend.robot, line 558 at r1](https://reviewable.io:443/reviews/openprocurement/robot_tests.broker.newtend/3#-KReW3oC_p786k-GJNzk:-KReW3oC_p786k-GJNzl:by3ix5i) ([raw file](https://github.com/openprocurement/robot_tests.broker.newtend/blob/417ade6cc393a2ba80ce935e31b464d9fb120acf/newtend.robot#L558)):_

> ``` RobotFramework
>   ${amount}=    Get From Dictionary     ${ARGUMENTS[2].data.value}    amount
>   Reload page
>   : FOR   ${INDEX}   IN RANGE    1    30
> ```

Шо цей цикл тут робить??? В чому його суть?

---

_[newtend.robot, line 559 at r1](https://reviewable.io:443/reviews/openprocurement/robot_tests.broker.newtend/3#-KReVlworGMuYgPdLXJS:-KReVlworGMuYgPdLXJT:b-fkyiua) ([raw file](https://github.com/openprocurement/robot_tests.broker.newtend/blob/417ade6cc393a2ba80ce935e31b464d9fb120acf/newtend.robot#L559)):_

> ``` RobotFramework
>   Reload page
>   : FOR   ${INDEX}   IN RANGE    1    30
>   \   Log To Console   .   no_newline=true
> ```

Цього не має бути в репозиторії.

---

_[newtend.robot, line 615 at r1](https://reviewable.io:443/reviews/openprocurement/robot_tests.broker.newtend/3#-KReX-DG4Kpl3GCadDx-:-KReX-DHz2LPehop1V28:b-kd86uw) ([raw file](https://github.com/openprocurement/robot_tests.broker.newtend/blob/417ade6cc393a2ba80ce935e31b464d9fb120acf/newtend.robot#L615)):_

> ``` RobotFramework
>   Input text        xpath=//textarea[@ng-model="chatData.message"]      ${answer}
>   click element     xpath=//button[@ng-click="sendAnswer()"]
>   reload page
> ```

Навіщо два рази перезавантажувати сторінку з інтервалом в дві секунди після того, як було відправлено відповідь?

---

_[newtend.robot, line 252 at r2](https://reviewable.io:443/reviews/openprocurement/robot_tests.broker.newtend/3#-KReXhmCxdx6DkR1jffc:-KReXhmCxdx6DkR1jffd:botfe6r) ([raw file](https://github.com/openprocurement/robot_tests.broker.newtend/blob/126159de45c156bc87a6588ceeba3fdc1721a189/newtend.robot#L252)):_

> ``` RobotFramework
>   Click element     xpath=//button[@ng-click="uploadDocument()"]
>   Select from list by index     xpath=//select[@id="documentType"]      2
>   Run keyword if     '${ARGUMENTS[0]}' == 'Newtend_Owner'    select from list by index   '2'  # xpath=//option[@value="notice"]
> ```

Де list першим аргументом в ківорді **`select from list by index`**? І чому `'2'`, а не `2`?

---

_[newtend.robot, line 381 at r2](https://reviewable.io:443/reviews/openprocurement/robot_tests.broker.newtend/3#-KReY4YPP8GZSBP393WP:-KReY4YPP8GZSBP393WQ:b-fkyiua) ([raw file](https://github.com/openprocurement/robot_tests.broker.newtend/blob/126159de45c156bc87a6588ceeba3fdc1721a189/newtend.robot#L381)):_

> ``` RobotFramework
> отримати інформацію про enquiryPeriod.endDate
>   ${enquiryPeriodEndDate}=   отримати текст із поля і показати на сторінці   enquiryPeriod.endDate      3   -1
>   Log to console    ${enquiryPeriodEndDate}
> ```

Цього не має бути в репозиторії.

---

_[newtend.robot, line 449 at r2](https://reviewable.io:443/reviews/openprocurement/robot_tests.broker.newtend/3#-KReYjip8RcrGQqM8ny2:-KReYjip8RcrGQqM8ny3:by5ke24) ([raw file](https://github.com/openprocurement/robot_tests.broker.newtend/blob/126159de45c156bc87a6588ceeba3fdc1721a189/newtend.robot#L449)):_

> ``` RobotFramework
> отримати інформацію про items[0].classification.description
>   ${classification_description}=   отримати текст із поля і показати на сторінці   items[0].classification.scheme
>   Run Keyword And Return If  '${classification_description}' == '66113000-5 - Права вимоги'   Convert To String   Права вимоги
> ```

Тут хардкод. @ykosaniak чому це потрапило в репозиторій?

---

_[newtend.robot, line 474 at r2](https://reviewable.io:443/reviews/openprocurement/robot_tests.broker.newtend/3#-KRee_AdiyY1GNqVwQgv:-KRee_AdiyY1GNqVwQgw:b-iyqdol) ([raw file](https://github.com/openprocurement/robot_tests.broker.newtend/blob/126159de45c156bc87a6588ceeba3fdc1721a189/newtend.robot#L474)):_

> ``` RobotFramework
> 
> отримати інформацію про items[0].unit.code
>   Fail  Не реалізований функціонал
> ```

Навіщо робити `Fail` і після того писати якийсь код?

---

_[newtend.robot, line 490 at r2](https://reviewable.io:443/reviews/openprocurement/robot_tests.broker.newtend/3#-KReZLCN9nW7FSJv7OTH:-KReZLCN9nW7FSJv7OTI:b-y8x539) ([raw file](https://github.com/openprocurement/robot_tests.broker.newtend/blob/126159de45c156bc87a6588ceeba3fdc1721a189/newtend.robot#L490)):_

> ``` RobotFramework
>   ...      ${ARGUMENTS[2]} =  3
>   ${period_interval}=  Get Broker Property By Username  ${ARGUMENTS[0]}  period_interval
>   ${ADDITIONAL_DATA}=  prepare_test_tender_data  ${period_interval}  multi
> ```

WTF???

---

_[newtend.robot, line 496 at r2](https://reviewable.io:443/reviews/openprocurement/robot_tests.broker.newtend/3#-KReZTAQgVQecfgCSJfl:-KReZTAQgVQecfgCSJfm:by5ke24) ([raw file](https://github.com/openprocurement/robot_tests.broker.newtend/blob/126159de45c156bc87a6588ceeba3fdc1721a189/newtend.robot#L496)):_

> ``` RobotFramework
>   Click Element                      ${locator.edit_tender}
>   Wait Until Page Contains Element   ${locator.edit.add_item}  10
>   Input text   ${locator.edit.description}   description
> ```

Тут хардкод. @ykosaniak чому це потрапило в репозиторій?

---

_[newtend.robot, line 506 at r2](https://reviewable.io:443/reviews/openprocurement/robot_tests.broker.newtend/3#-KReYxmbHgUzZWzI_nVG:-KReYxmbHgUzZWzI_nVH:b7ci7u) ([raw file](https://github.com/openprocurement/robot_tests.broker.newtend/blob/126159de45c156bc87a6588ceeba3fdc1721a189/newtend.robot#L506)):_

> ``` RobotFramework
> ###  Не видно контролів додати пропозицію в хромі, потрібно скролити, скрол не працює. Обхід: додати лише 1 пропозицію + редагувати description для скролу.
>   Click Element    ${locator.edit.add_item}
>   Додати придмет   ${items[1]}   1
> ```

**`придмет`** -> **`предмет`**...
Що таке **`${items}`** в даному контексті?
Змінна не оголошена в аргументах і не оголошена взагалі. 

---

_[newtend.robot, line 509 at r2](https://reviewable.io:443/reviews/openprocurement/robot_tests.broker.newtend/3#-KRef1PI-LTUESxrGFSy:-KRef1PI-LTUESxrGFSz:b-77bqdt) ([raw file](https://github.com/openprocurement/robot_tests.broker.newtend/blob/126159de45c156bc87a6588ceeba3fdc1721a189/newtend.robot#L509)):_

> ``` RobotFramework
> 
> забрати позицію
>   Click Element   xpath=//a[@title="Добавить лот"]/preceding-sibling::a
> ```

Мені здається, що `забрати пропозицію` і `Добавить лот` не пов'язані між собою. Нє? 

---

_[newtend.robot, line 570 at r2](https://reviewable.io:443/reviews/openprocurement/robot_tests.broker.newtend/3#-KRefdhWqBeGGuQImWiA:-KRefdhWqBeGGuQImWiB:b-jbmrao) ([raw file](https://github.com/openprocurement/robot_tests.broker.newtend/blob/126159de45c156bc87a6588ceeba3fdc1721a189/newtend.robot#L570)):_

> ``` RobotFramework
>   ${day}=   Get Substring   ${ARGUMENTS[0]}   0   2
>   ${month}=   Get Substring   ${ARGUMENTS[0]}  3   6
>   ${rest}=   Get Substring   ${ARGUMENTS[0]}   5
> ```

Чому тут `5`?

---

_[newtend.robot, line 623 at r2](https://reviewable.io:443/reviews/openprocurement/robot_tests.broker.newtend/3#-KRefsvDgAqMFCPTr7sT:-KRefsvDgAqMFCPTr7sU:bnl8wm6) ([raw file](https://github.com/openprocurement/robot_tests.broker.newtend/blob/126159de45c156bc87a6588ceeba3fdc1721a189/newtend.robot#L623)):_

> ``` RobotFramework
>     Input Text              xpath=//input[@name="amount"]         ${ARGUMENTS[3]}
>     ${agree}=   Get Matching Xpath Count     xpath=//input[@name="agree"]
>     run keyword if  '${agree}' == '1'     Click element   xpath=//input[@name="agree"]
> ```

А якщо **`${agree}`** буде не `'1'`? 
Не існує якогось конкретнішого xpath'у?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests.broker.newtend/3#-:-KReg9CE17HQFW9nZeck:b-vi15na)_

**Comment by selurvedu** [comment]
> Навіщо додавати в репозиторій стільки закоментованого коду?

@mykhaly, аби було? :)

---

Review status: all files reviewed at latest revision, 18 unresolved discussions.

---

_[newtend.robot, line 141 at r1](https://reviewable.io:443/reviews/openprocurement/robot_tests.broker.newtend/3#-KReTw8p_P2y_VHOsjUv:-KRgcUZkpaASGgV5ICFN:b-34y43v) ([raw file](https://github.com/openprocurement/robot_tests.broker.newtend/blob/417ade6cc393a2ba80ce935e31b464d9fb120acf/newtend.robot#L141)):_
<details><summary>

<i>Previously, mykhaly (Yurii Mykhalchuk) wrote…</i></summary>



> Тут хардкод. @ykosaniak чому це потрапило в репозиторій?
> </details>
> Наш код це не перевіряє (бо базується на `2.3.x`), тому your argument is invalid. :)

---

_[newtend.robot, line 161 at r1](https://reviewable.io:443/reviews/openprocurement/robot_tests.broker.newtend/3#-KReUI3nlqQdS6x9dVOc:-KRgcLISDkTAXL59JqVV:b-34y43v) ([raw file](https://github.com/openprocurement/robot_tests.broker.newtend/blob/417ade6cc393a2ba80ce935e31b464d9fb120acf/newtend.robot#L161)):_
<details><summary>

<i>Previously, mykhaly (Yurii Mykhalchuk) wrote…</i></summary>



> Тут хардкод. @ykosaniak чому це потрапило в репозиторій?
> </details>
> Наш код це не перевіряє (бо базується на `2.3.x`), тому your argument is invalid. :)

---

_[newtend.robot, line 558 at r1](https://reviewable.io:443/reviews/openprocurement/robot_tests.broker.newtend/3#-KReW3oC_p786k-GJNzk:-KRgdxulzc_dBrPy56I_:b-swvzt7) ([raw file](https://github.com/openprocurement/robot_tests.broker.newtend/blob/417ade6cc393a2ba80ce935e31b464d9fb120acf/newtend.robot#L558)):_
<details><summary>

<i>Previously, mykhaly (Yurii Mykhalchuk) wrote…</i></summary>



> Шо цей цикл тут робить??? В чому його суть?
> </details>
> Rertry – чекає 90 секунд, поки не знайде потрібну кнопку.

---

_[newtend.robot, line 449 at r2](https://reviewable.io:443/reviews/openprocurement/robot_tests.broker.newtend/3#-KReYjip8RcrGQqM8ny2:-KRgeGD5EIU9dgR14j2l:b-34y43v) ([raw file](https://github.com/openprocurement/robot_tests.broker.newtend/blob/126159de45c156bc87a6588ceeba3fdc1721a189/newtend.robot#L449)):_
<details><summary>

<i>Previously, mykhaly (Yurii Mykhalchuk) wrote…</i></summary>



> Тут хардкод. @ykosaniak чому це потрапило в репозиторій?
> </details>
> Наш код це не перевіряє (бо базується на `2.3.x`), тому your argument is invalid. :)

---

_[newtend.robot, line 474 at r2](https://reviewable.io:443/reviews/openprocurement/robot_tests.broker.newtend/3#-KRee_AdiyY1GNqVwQgv:-KRgczz2o3vNM_TKNMmZ:brz6x3q) ([raw file](https://github.com/openprocurement/robot_tests.broker.newtend/blob/126159de45c156bc87a6588ceeba3fdc1721a189/newtend.robot#L474)):_
<details><summary>

<i>Previously, mykhaly (Yurii Mykhalchuk) wrote…</i></summary>



> Навіщо робити `Fail` і після того писати якийсь код?
> </details>
> Щоб в консоль і лог писався явний меседж про те, що ківорд ще не готовий, це зекономить час виконання тестів і зусилля на розбір того, що ж там відбулось.

---

_[newtend.robot, line 490 at r2](https://reviewable.io:443/reviews/openprocurement/robot_tests.broker.newtend/3#-KReZLCN9nW7FSJv7OTH:-KRgcl2AHgISZHhCij7s:b157ugr) ([raw file](https://github.com/openprocurement/robot_tests.broker.newtend/blob/126159de45c156bc87a6588ceeba3fdc1721a189/newtend.robot#L490)):_
<details><summary>

<i>Previously, mykhaly (Yurii Mykhalchuk) wrote…</i></summary>



> WTF???
> </details>
> Цей ківорд не використовується в `singleItem*`, очевидно же!

---

_[newtend.robot, line 496 at r2](https://reviewable.io:443/reviews/openprocurement/robot_tests.broker.newtend/3#-KReZTAQgVQecfgCSJfl:-KRgeP1QkRYH1O-1d4-w:b-34y43v) ([raw file](https://github.com/openprocurement/robot_tests.broker.newtend/blob/126159de45c156bc87a6588ceeba3fdc1721a189/newtend.robot#L496)):_
<details><summary>

<i>Previously, mykhaly (Yurii Mykhalchuk) wrote…</i></summary>



> Тут хардкод. @ykosaniak чому це потрапило в репозиторій?
> </details>
> Наш код це не перевіряє (бо базується на `2.3.x`), тому your argument is invalid. :)

---

_[newtend.robot, line 506 at r2](https://reviewable.io:443/reviews/openprocurement/robot_tests.broker.newtend/3#-KReYxmbHgUzZWzI_nVG:-KRgdCvCVOnj0_ABxtWb:b-5hg1nk) ([raw file](https://github.com/openprocurement/robot_tests.broker.newtend/blob/126159de45c156bc87a6588ceeba3fdc1721a189/newtend.robot#L506)):_
<details><summary>

<i>Previously, mykhaly (Yurii Mykhalchuk) wrote…</i></summary>



> **`придмет`** -> **`предмет`**...
> Що таке **`${items}`** в даному контексті?
> Змінна не оголошена в аргументах і не оголошена взагалі. 
> 
> </details>
> Це код річної давності (може й більше), який не використовується (і `придмет` колись був в КОЖНОМУ драйвері), тому забий.

---

_[newtend.robot, line 570 at r2](https://reviewable.io:443/reviews/openprocurement/robot_tests.broker.newtend/3#-KRefdhWqBeGGuQImWiA:-KRgfOrZoAsByex9_R1e:b-66m257) ([raw file](https://github.com/openprocurement/robot_tests.broker.newtend/blob/126159de45c156bc87a6588ceeba3fdc1721a189/newtend.robot#L570)):_
<details><summary>

<i>Previously, mykhaly (Yurii Mykhalchuk) wrote…</i></summary>



> Чому тут `5`?
> </details>
> Ківорд не використовується.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests.broker.newtend/3#-:-KRgcEDb-WjSD5-MA-5o:b-zcpz9t)_

**Comment by mykhaly** [comment]
:/

---

Review status: all files reviewed at latest revision, 18 unresolved discussions.

---

_[newtend.robot, line 141 at r1](https://reviewable.io:443/reviews/openprocurement/robot_tests.broker.newtend/3#-KReTw8p_P2y_VHOsjUv:-KRgrGnwMC0bBgMB9d9G:baj030) ([raw file](https://github.com/openprocurement/robot_tests.broker.newtend/blob/417ade6cc393a2ba80ce935e31b464d9fb120acf/newtend.robot#L141)):_
<details><summary>

<i>Previously, selurvedu wrote…</i></summary>



> Наш код це не перевіряє (бо базується на `2.3.x`), тому your argument is invalid. :)
> </details>
> Те, що наш код щось не перевіряє, не означає, що то можна хардкодити.

---

_[newtend.robot, line 161 at r1](https://reviewable.io:443/reviews/openprocurement/robot_tests.broker.newtend/3#-KReUI3nlqQdS6x9dVOc:-KRgrWiYVeLdlJEUa0dd:b-e69vjq) ([raw file](https://github.com/openprocurement/robot_tests.broker.newtend/blob/417ade6cc393a2ba80ce935e31b464d9fb120acf/newtend.robot#L161)):_
<details><summary>

<i>Previously, selurvedu wrote…</i></summary>



> Наш код це не перевіряє (бо базується на `2.3.x`), тому your argument is invalid. :)
> </details>
> Окей. Тут згоден, що цієї функціональності не мало би бути.

---

_[newtend.robot, line 558 at r1](https://reviewable.io:443/reviews/openprocurement/robot_tests.broker.newtend/3#-KReW3oC_p786k-GJNzk:-KRgtTkQJdq2bnobdqdV:bgy8smm) ([raw file](https://github.com/openprocurement/robot_tests.broker.newtend/blob/417ade6cc393a2ba80ce935e31b464d9fb120acf/newtend.robot#L558)):_
<details><summary>

<i>Previously, selurvedu wrote…</i></summary>



> Rertry – чекає 90 секунд, поки не знайде потрібну кнопку.
> </details>
> В інших "конструкціях" такого типу я бачив всередині циклу `Reload Page`. Тут його немає.
> Чи на сайті має виконатися якийсь ajax?

---

_[newtend.robot, line 449 at r2](https://reviewable.io:443/reviews/openprocurement/robot_tests.broker.newtend/3#-KReYjip8RcrGQqM8ny2:-KRgs1TRN_UmWh8JYddL:b-gcd59z) ([raw file](https://github.com/openprocurement/robot_tests.broker.newtend/blob/126159de45c156bc87a6588ceeba3fdc1721a189/newtend.robot#L449)):_
<details><summary>

<i>Previously, selurvedu wrote…</i></summary>



> Наш код це не перевіряє (бо базується на `2.3.x`), тому your argument is invalid. :)
> </details>
> https://github.com/openprocurement/robot_tests/blob/eauction/op_robot_tests/tests_files/singleItemAuction.robot#L252

---

_[newtend.robot, line 474 at r2](https://reviewable.io:443/reviews/openprocurement/robot_tests.broker.newtend/3#-KRee_AdiyY1GNqVwQgv:-KRgsAMLsTJjT8CdFosr:b-400gz) ([raw file](https://github.com/openprocurement/robot_tests.broker.newtend/blob/126159de45c156bc87a6588ceeba3fdc1721a189/newtend.robot#L474)):_
<details><summary>

<i>Previously, selurvedu wrote…</i></summary>



> Щоб в консоль і лог писався явний меседж про те, що ківорд ще не готовий, це зекономить час виконання тестів і зусилля на розбір того, що ж там відбулось.
> </details>
> Ну так якщо ківорд не готовий, то чому в ньому далі є якийсь код?
> 
> ```
>   ${unit_code}=   отримати текст із поля і показати на сторінці   items[0].unit.code
>   [return]  ${unit_code}
> ```

---

_[newtend.robot, line 490 at r2](https://reviewable.io:443/reviews/openprocurement/robot_tests.broker.newtend/3#-KReZLCN9nW7FSJv7OTH:-KRgsau8HYAqRhhIblqC:b9oeaqm) ([raw file](https://github.com/openprocurement/robot_tests.broker.newtend/blob/126159de45c156bc87a6588ceeba3fdc1721a189/newtend.robot#L490)):_
<details><summary>

<i>Previously, selurvedu wrote…</i></summary>



> Цей ківорд не використовується в `singleItem*`, очевидно же!
> </details>
> Мені не було очевидно :/
> Мій завтик.

---

_[newtend.robot, line 506 at r2](https://reviewable.io:443/reviews/openprocurement/robot_tests.broker.newtend/3#-KReYxmbHgUzZWzI_nVG:-KRgsVepuBx5MnBZvxAW:b2ni922) ([raw file](https://github.com/openprocurement/robot_tests.broker.newtend/blob/126159de45c156bc87a6588ceeba3fdc1721a189/newtend.robot#L506)):_
<details><summary>

<i>Previously, selurvedu wrote…</i></summary>



> Це код річної давності (може й більше), який не використовується (і `придмет` колись був в КОЖНОМУ драйвері), тому забий.
> </details>
> o_O

---

_[newtend.robot, line 570 at r2](https://reviewable.io:443/reviews/openprocurement/robot_tests.broker.newtend/3#-KRefdhWqBeGGuQImWiA:-KRgtG9Jj3ld00n7MgDt:bjft92s) ([raw file](https://github.com/openprocurement/robot_tests.broker.newtend/blob/126159de45c156bc87a6588ceeba3fdc1721a189/newtend.robot#L570)):_
<details><summary>

<i>Previously, selurvedu wrote…</i></summary>



> Ківорд не використовується.
> </details>
> По ходу використовується
> https://github.com/openprocurement/robot_tests/blob/eauction/op_robot_tests/tests_files/singleItemAuction.robot#L353

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests.broker.newtend/3#-:-KRgtn6_bZap3QtuRWm4:b32vi2)_

**Comment by selurvedu** [comment]
Review status: all files reviewed at latest revision, 18 unresolved discussions.

---

_[newtend.robot, line 141 at r1](https://reviewable.io:443/reviews/openprocurement/robot_tests.broker.newtend/3#-KReTw8p_P2y_VHOsjUv:-KRmqt5gmOIjuG5PF_tN:btux6i3) ([raw file](https://github.com/openprocurement/robot_tests.broker.newtend/blob/417ade6cc393a2ba80ce935e31b464d9fb120acf/newtend.robot#L141)):_
<details><summary>

<i>Previously, mykhaly (Yurii Mykhalchuk) wrote…</i></summary>



> Те, що наш код щось не перевіряє, не означає, що то можна хардкодити.
> </details>
> Ну написали ж "Sorry" :)
> Як буде програмна перевірка (а точніше Faker), то це хоч-не-хоч, а перероблять.

---

_[newtend.robot, line 558 at r1](https://reviewable.io:443/reviews/openprocurement/robot_tests.broker.newtend/3#-KReW3oC_p786k-GJNzk:-KRmqRRvuonBbUlvXATS:b-nnga0y) ([raw file](https://github.com/openprocurement/robot_tests.broker.newtend/blob/417ade6cc393a2ba80ce935e31b464d9fb120acf/newtend.robot#L558)):_
<details><summary>

<i>Previously, mykhaly (Yurii Mykhalchuk) wrote…</i></summary>



> В інших "конструкціях" такого типу я бачив всередині циклу `Reload Page`. Тут його немає.
> Чи на сайті має виконатися якийсь ajax?
> </details>
> Очевидно, так.

---

_[newtend.robot, line 252 at r2](https://reviewable.io:443/reviews/openprocurement/robot_tests.broker.newtend/3#-KReXhmCxdx6DkR1jffc:-KRmrPZZgJRW9mH6RXDg:bdj0w0k) ([raw file](https://github.com/openprocurement/robot_tests.broker.newtend/blob/126159de45c156bc87a6588ceeba3fdc1721a189/newtend.robot#L252)):_
<details><summary>

<i>Previously, mykhaly (Yurii Mykhalchuk) wrote…</i></summary>



> Де list першим аргументом в ківорді **`select from list by index`**? І чому `'2'`, а не `2`?
> </details>
> Тут явна помилка, в наступному коміті цей рядок закоментували для подальшої доробки.

---

_[newtend.robot, line 449 at r2](https://reviewable.io:443/reviews/openprocurement/robot_tests.broker.newtend/3#-KReYjip8RcrGQqM8ny2:-KRmowx9FGlCA3RD9-Ax:byesetr) ([raw file](https://github.com/openprocurement/robot_tests.broker.newtend/blob/126159de45c156bc87a6588ceeba3fdc1721a189/newtend.robot#L449)):_
<details><summary>

<i>Previously, mykhaly (Yurii Mykhalchuk) wrote…</i></summary>



> https://github.com/openprocurement/robot_tests/blob/eauction/op_robot_tests/tests_files/singleItemAuction.robot#L252
> </details>
> В нас лише 1 CAV – `66113000-5 - Права вимоги`, я про це. Фейкера нема.

---

_[newtend.robot, line 474 at r2](https://reviewable.io:443/reviews/openprocurement/robot_tests.broker.newtend/3#-KRee_AdiyY1GNqVwQgv:-KRmsHflPZ1B-1zTDJkK:b-f2mt48) ([raw file](https://github.com/openprocurement/robot_tests.broker.newtend/blob/126159de45c156bc87a6588ceeba3fdc1721a189/newtend.robot#L474)):_
<details><summary>

<i>Previously, mykhaly (Yurii Mykhalchuk) wrote…</i></summary>



> Ну так якщо ківорд не готовий, то чому в ньому далі є якийсь код?
> 
> ```
>   ${unit_code}=   отримати текст із поля і показати на сторінці   items[0].unit.code
>   [return]  ${unit_code}
> ```
> 
> </details>
> Бо ківорд насправді готовий, але майданчик не показує item unit code. Пам'ятаєш, ти ще тег такий додавав для exclude?

---

_[newtend.robot, line 509 at r2](https://reviewable.io:443/reviews/openprocurement/robot_tests.broker.newtend/3#-KRef1PI-LTUESxrGFSy:-KRmpDzbmTm0_IerBohe:brvzlz3) ([raw file](https://github.com/openprocurement/robot_tests.broker.newtend/blob/126159de45c156bc87a6588ceeba3fdc1721a189/newtend.robot#L509)):_
<details><summary>

<i>Previously, mykhaly (Yurii Mykhalchuk) wrote…</i></summary>



> Мені здається, що `забрати пропозицію` і `Добавить лот` не пов'язані між собою. Нє? 
> </details>
> Бачиш `preceding-sibling`? Переклади. :)
> Це не найкращий локатор, але я впевнений, що він попадає куди треба (або хоча б на момент написання попадав).

---

_[newtend.robot, line 570 at r2](https://reviewable.io:443/reviews/openprocurement/robot_tests.broker.newtend/3#-KRefdhWqBeGGuQImWiA:-KRmpbGytiSYze52Q5Oc:b-i2ijfs) ([raw file](https://github.com/openprocurement/robot_tests.broker.newtend/blob/126159de45c156bc87a6588ceeba3fdc1721a189/newtend.robot#L570)):_
<details><summary>

<i>Previously, mykhaly (Yurii Mykhalchuk) wrote…</i></summary>



> По ходу використовується
> https://github.com/openprocurement/robot_tests/blob/eauction/op_robot_tests/tests_files/singleItemAuction.robot#L353
> </details>
> По-перше, `отримати інформацію про QUESTIONS[0].date` (єдине місце, де є виклик цього ківорду) не схоже що викликається з наших сценаріїв, або я заплутався.
> По-друге, навіть якщо воно мало б викликатись, то в цьому драйвері я не знайшов підтримки object_id, тому, ймовірно, дата порівнялась би з `date` – датою тендера (див. код за твоїм лінком).

Ми ж переробляли роботу з запитаннями в `robot_tests` саме через ці проблеми.

---

_[newtend.robot, line 623 at r2](https://reviewable.io:443/reviews/openprocurement/robot_tests.broker.newtend/3#-KRefsvDgAqMFCPTr7sT:-KRmqaG-WeaVr8Y0tk7S:bfvur39) ([raw file](https://github.com/openprocurement/robot_tests.broker.newtend/blob/126159de45c156bc87a6588ceeba3fdc1721a189/newtend.robot#L623)):_
<details><summary>

<i>Previously, mykhaly (Yurii Mykhalchuk) wrote…</i></summary>



> А якщо **`${agree}`** буде не `'1'`? 
> Не існує якогось конкретнішого xpath'у?
> </details>
> Навряд чи на сторінці буде більше одного чекбоксу "Я погоджуюсь" – він або буде, або не буде.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests.broker.newtend/3)_

**Pull request merged**
