### PR TITLE
Latest updates

### PR DESCRIPTION
**Pull request by SlaOne**
all 3 roles work fine

---
This change is [Reviewable](https://reviewable.io/reviews/openprocurement/robot_tests.broker.newtend/5)

### CODE REVIEW

**Comment by annawzz** [comment]
Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

_[newtend.robot, line 103 at r1](https://reviewable.io:443/reviews/openprocurement/robot_tests.broker.newtend/5#-KVdzIPAnst9xnDJsdZP:-KVdzIPBzb7wheYy712j:bh3mkb7) ([raw file](https://github.com/openprocurement/robot_tests.broker.newtend/blob/be6713ca0d2919aa7544e894fa57b43b029ce763/newtend.robot#L103)):_

> ``` RobotFramework
>   ${dgfID}=         Get From Dictionary   ${ARGUMENTS[1].data}               dgfID
>   ${budget}=        Get From Dictionary   ${ARGUMENTS[1].data.value}         amount
>   ${guarantee}=     get from dictionary   ${ARGUMENTS[1].data.guarantee}     amount
> ```

Чому тут 'get from dictionary' з маленької букви? Всюди повинен бути однаковий синтаксис.

---

_[newtend.robot, line 153 at r1](https://reviewable.io:443/reviews/openprocurement/robot_tests.broker.newtend/5#-KVdzZFqtfAfvDTCTUbB:-KVdzZFqtfAfvDTCTUbC:b-kkwye9) ([raw file](https://github.com/openprocurement/robot_tests.broker.newtend/blob/be6713ca0d2919aa7544e894fa57b43b029ce763/newtend.robot#L153)):_

> ``` RobotFramework
>   click element   ${locator.items[0].classification.scheme}
>   sleep     5
>   input text      id=classifier-search-field    ${classification_id}
> ```

'input text' також маленькими... робіть всюди однаковий синтаксис, тут і нижче.

---

_[newtend.robot, line 303 at r1](https://reviewable.io:443/reviews/openprocurement/robot_tests.broker.newtend/5#-KVdwjmA40tujM9BERcL:-KVdwjmB425vxxKXhpwd:bdzh7m7) ([raw file](https://github.com/openprocurement/robot_tests.broker.newtend/blob/be6713ca0d2919aa7544e894fa57b43b029ce763/newtend.robot#L303)):_

> ``` RobotFramework
>   ${procuringEntity_name}=   отримати текст із поля і показати на сторінці   procuringEntity.name
> #  ${procuringEntity_name}=  Set Variable If  '${username}' == 'Newtend_Owner'  update_data_for_newtend   ${procuringEntity_name}
> #  log to console  ${username}
> ```

Варто забрати закоментоване, якщо воно непотрібне.

---

_[newtend_service.py, line 51 at r1](https://reviewable.io:443/reviews/openprocurement/robot_tests.broker.newtend/5#-KVe-EPnLeHF_1JVqkZ-:-KVe-EPo2XrgEsB7iZPl:b-r9eqk7) ([raw file](https://github.com/openprocurement/robot_tests.broker.newtend/blob/be6713ca0d2919aa7544e894fa57b43b029ce763/newtend_service.py#L51)):_

> ``` Python
> # ======================================
> '''
> ```

Явно непотрібні тут коментарі.

---

_[newtend_service.py, line 69 at r1](https://reviewable.io:443/reviews/openprocurement/robot_tests.broker.newtend/5#-KVe-Kq0oo-O3yiaAwnT:-KVe-Kq0oo-O3yiaAwnU:b-n1e1at) ([raw file](https://github.com/openprocurement/robot_tests.broker.newtend/blob/be6713ca0d2919aa7544e894fa57b43b029ce763/newtend_service.py#L69)):_

> ``` Python
>     # tender_data['data']['procuringEntity']['name'] = u"Bank fool name"
>     return tender_data
> ```

Лишні коментарі тут і нижче.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests.broker.newtend/5)_

**Comment by kosaniak** [comment]
Review status: 0 of 2 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

_[newtend.robot, line 273 at r1](https://reviewable.io:443/reviews/openprocurement/robot_tests.broker.newtend/5#-KVdaUfbOKn4atDwTSoy:-KVdaUfc8R6JRzA3JaQW:bmkf4ud) ([raw file](https://github.com/openprocurement/robot_tests.broker.newtend/blob/be6713ca0d2919aa7544e894fa57b43b029ce763/newtend.robot#L273)):_

> ``` RobotFramework
> отримати інформацію про auctionId
>   ${tenderId}=   отримати текст із поля і показати на сторінці   auctionId
>   [return]  ${tenderId}
> ```

варто зміну tenderId переназвати на auctionId

---

_[newtend_service.py, line 94 at r1](https://reviewable.io:443/reviews/openprocurement/robot_tests.broker.newtend/5#-KVe0fKuKU_jhs9-4nTv:-KVe0fKuKU_jhs9-4nTw:b-qm8u8s) ([raw file](https://github.com/openprocurement/robot_tests.broker.newtend/blob/be6713ca0d2919aa7544e894fa57b43b029ce763/newtend_service.py#L94)):_

> ``` Python
>     time_zone = timezone('Europe/Kiev')
>     localized_date = time_zone.localize(new_date)
>     return localized_date.strftime("%Y-%m-%d %H:%M:%S%z")
> ```

add_timezone_to_date і get_time_with_offset  однакові, не треба їх дублювати

---

_[newtend_service.py, line 97 at r1](https://reviewable.io:443/reviews/openprocurement/robot_tests.broker.newtend/5#-KVe0FVXckHf79wYUDeq:-KVe0FVXckHf79wYUDer:boo7n4c) ([raw file](https://github.com/openprocurement/robot_tests.broker.newtend/blob/be6713ca0d2919aa7544e894fa57b43b029ce763/newtend_service.py#L97)):_

> ``` Python
> 
> 
> def convert_newtend_date_to_iso_format(date_time_from_ui):
> ```

чим ця функція відрізняється від convert_newtend_auction_date_format? Якщо лише назвою, то треба залишити одну.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests.broker.newtend/5)_

**Comment by kosaniak** [comment]
Review status: 0 of 2 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

_[newtend.robot, line 627 at r1](https://reviewable.io:443/reviews/openprocurement/robot_tests.broker.newtend/5#-KVe15dfWr7T22EYqrWh:-KVe15dfWr7T22EYqrWi:b-pixwqo) ([raw file](https://github.com/openprocurement/robot_tests.broker.newtend/blob/be6713ca0d2919aa7544e894fa57b43b029ce763/newtend.robot#L627)):_

> ``` RobotFramework
>   sleep     2
>   click element  xpath=//button[@ng-click="closeBids(lot.awardId, lot.contractId)"]
>   sleep     2
> ```

тут і вище сліпи потрібно замінити на wait until

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests.broker.newtend/5)_

**Comment by annawzz** [comment]
Review status: 0 of 2 files reviewed at latest revision, 13 unresolved discussions, some commit checks failed.

---

_[newtend.robot, line 470 at r1](https://reviewable.io:443/reviews/openprocurement/robot_tests.broker.newtend/5#-KVe0Hru-i1GH6wQjFLn:-KVe0HrvWJx782Gh9pN2:b-cylyth) ([raw file](https://github.com/openprocurement/robot_tests.broker.newtend/blob/be6713ca0d2919aa7544e894fa57b43b029ce763/newtend.robot#L470)):_

> ``` RobotFramework
>   \   sleep     3
>   \   ${count}=   Get Matching Xpath Count   xpath=//button[@ng-click="placeBid()"]
>   \   Exit For Loop If   '${count}' == '1'
> ```

Чи можна замість ось такого циклу використовувати простішу конструкцію, щось типу Wait Until... ?

---

_[newtend.robot, line 550 at r1](https://reviewable.io:443/reviews/openprocurement/robot_tests.broker.newtend/5#-KVe0wz4YfpLIZcmvQgz:-KVe0wz4YfpLIZcmvQh-:b-ydptur) ([raw file](https://github.com/openprocurement/robot_tests.broker.newtend/blob/be6713ca0d2919aa7544e894fa57b43b029ce763/newtend.robot#L550)):_

> ``` RobotFramework
>   \   ${count}=   Get Matching Xpath Count   xpath=//a[@class="auction-link ng-binding"]
>   \   ${link}=    get element attribute      xpath=//a[@target="_blank"]@href
>   \   Exit For Loop If   '${count}' == '1' and '${link}' != 'None'
> ```

Так само як вище.

---

_[newtend.robot, line 570 at r1](https://reviewable.io:443/reviews/openprocurement/robot_tests.broker.newtend/5#-KVe10668Z2L0h-Iu-ak:-KVe10668Z2L0h-Iu-al:b-ydptur) ([raw file](https://github.com/openprocurement/robot_tests.broker.newtend/blob/be6713ca0d2919aa7544e894fa57b43b029ce763/newtend.robot#L570)):_

> ``` RobotFramework
>   \   ${count}=   Get Matching Xpath Count   xpath=//a[@class="auction-link ng-binding"]
>   \   ${link}=    get element attribute      xpath=//a[@target="_blank"]@href
>   \   Exit For Loop If   '${count}' == '1' and '${link}' != 'None'
> ```

Так само як вище.

---

_[newtend.robot, line 598 at r1](https://reviewable.io:443/reviews/openprocurement/robot_tests.broker.newtend/5#-KVe13CsVogmgXugDJeY:-KVe13CsVogmgXugDJeZ:b-ydptur) ([raw file](https://github.com/openprocurement/robot_tests.broker.newtend/blob/be6713ca0d2919aa7544e894fa57b43b029ce763/newtend.robot#L598)):_

> ``` RobotFramework
>   \   ${count}=   Get Matching Xpath Count   xpath=//div[@class="ng-binding"]
>   \   ${text}=   get text   xpath=//div[@class="ng-binding"]
>   \   Exit For Loop If   '${count}' == '1' and '${text}' != ''
> ```

Так само як вище.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests.broker.newtend/5)_

**Pull request closed without merging**
